(define (problem hanoi-6-0)
  (:domain hanoi)
  (:objects 
    a b c d e f t1 t2 t3 - truc)
  (:init 
    (clearrr f)
    (clearrr t2)
    (clearrr t3)
    (on f e)
    (on e d)
    (on d c)
    (on c b)
    (on b a)
    (on a t1)
    (small a b) (small a c) (small a d) (small a e) (small a f) (small t1 a) (small t2 a) (small t3 a)
    (small b c) (small b d) (small b e) (small b f) (small t1 b) (small t2 b) (small t3 b)
    (small c d) (small c e) (small c f) (small t1 c) (small t2 c) (small t3 c)
    (small d e) (small d f) (small t1 d) (small t2 d) (small t3 d)
    (small e f) (small t1 e) (small t2 e) (small t3 e)
    (small t1 f) (small t2 f) (small t3 f))
  (:goal 
    (and 
      (clearrr f)
      (on f e)
      (on e d)
      (on d c)
      (on c b)
      (on b a)
      (on a t3)))
)