(define (problem sokoban-6-0)
  (:domain sokoban)
  (:objects 
    l1 l2 l3 l4 l5 l6-1 - lieu )
  (:init 
    (Pon l6-1)
    (Con l2)
    (Con l5)
    (isG l1)
    (clear l1)
    (clear l3)
    (clear l4)
    (clear l5)
    (clear l6-1)
    (connectR l1 l2)
    (connectD l1 l4)
    (connectR l2 l3)
    (connectL l2 l1)
    (connectD l2 l5)
    (connectL l3 l2)
    (connectD l3 l6-1)
    (connectU l4 l1)
    (connectR l4 l5)
    (connectL l5 l4)
    (connectU l5 l2)
    (connectR l5 l6-1)
    (connectL l6-1 l5)
    (connectU l6-1 l3)
    )
  (:goal 
    (and (Con l1)
    (isG l1)
    (Con l4)))
    )
