(define (problem taquin-2-0)
  (:domain taquin)
  (:objects 
    a b c - piece l1 l2 l3 l4 - lieu)
  (:init 
    (on a l2)
    (on b l4)
    (on c l3)
    (clear l1)
    (connect l1 l2)
    (connect l1 l3)
    (connect l2 l1)
    (connect l2 l4)
    (connect l3 l1)
    (connect l3 l4)
    (connect l4 l2)
    (connect l4 l3)
    )
  (:goal 
    (and (on a l1)
    (on b l2)
    (on c l3))
    )
)