(define (problem taquin-2-0)
  (:domain taquin)
  (:objects 
    a b c d e f g h - piece l1 l2 l3 l4 l5 l6 l7 l8 l9 - lieu)
  (:init 
    (on d l1)
    (on f l2)
    (on e l3)
    (on c l4)
    (on b l5)
    (on h l6)
    (on g l7)
    (on a l8)
    (clear l9)
    (connect l1 l2)
    (connect l1 l4)
    (connect l2 l1)
    (connect l2 l5)
    (connect l2 l3)
    (connect l3 l2)
    (connect l3 l6)
    (connect l4 l1)
    (connect l4 l5)
    (connect l4 l7)
    (connect l5 l2)
    (connect l5 l4)
    (connect l5 l6)
    (connect l5 l8)
    (connect l6 l5)
    (connect l6 l3)
    (connect l6 l9)
    (connect l7 l4)
    (connect l7 l8)
    (connect l8 l7)
    (connect l8 l5)
    (connect l8 l9)
    (connect l9 l6)
    (connect l9 l8)
    )
  (:goal 
    (and (on a l1)
    (on b l2)
    (on c l3)
    (on d l4)
    (on e l5)
    (on f l6)
    (on g l7)
    (on h l8))
    )
)